backend:
  name: github
  repo: Davao-IT-Solutions/IT-Solutions-Colorlib-Nuxt

site_url: https://davao-it-solutions.netlify.app

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Type", name: "type", widget: "string", required: false}
      - {label: "Language", name: "language", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: summary, widget: text, required: true, pattern: ['.{164,220}', "Must be within 164 and 220 characters"]}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Author Link", name: "authorlink", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Summary", name: summary, widget: text, required: true, pattern: ['.{10,220}', "Must be within 10 and 220 characters"]}
      - {label: "CSS Icon", name: "css_icon", widget: "string", required: false}
      - {label: "Order", name: "order", widget: number, required: false, default: 0}
      - {label: "Display on Hero", name: "display_hero", required: false, widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'content/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }
      - name: 'stats'
        label: 'Statistics'
        file: 'content/statistics.json'
        description: 'Our Records Config'
        fields:
          - { label: 'Projects Completed', name: 'projects_completed', widget: 'number' }
          - { label: 'Happy Clients', name: 'happy_clients', widget: 'number' }
          - { label: 'Business Partners', name: 'business_partners', widget: 'number' }
      - name: 'contact'
        label: 'Contact Us'
        file: 'content/contacts.json'
        description: 'Contact Us Page'
        fields:
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Phone Number', name: 'phone', widget: 'string' }
          - { label: 'Email Address', name: 'email', widget: 'string' }
          - { label: 'Map URL', name: 'map_url', widget: 'string' }
          - { label: 'Facebook Page URL', name: 'facebook_url', widget: 'string' }
      - name: 'footer_links'
        label: 'Footer Links'
        file: 'content/footer_links.json'
        description: 'Footer Links'
        fields:
          - name: links
            label: Links
            label_singular: 'Link'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'First and Last' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
